"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": false

"files":
  [
    {
      "source": "src/translations/en.yml",
      "translation": "src/translations/%two_letters_code%.yml",
    },
  ]
