name: Crowdin Action

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  # Visit https://crowdin.com/settings#api-key to create this token
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true

      - name: Pre-translate
        uses: crowdin/github-action@v2
        with:
          command: "pre-translate"
          command_args: "--method ai --ai-prompt 129657 --no-progress"

      - name: Download translations
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          download_translations: true
          create_pull_request: true
